[versions]
assertj = "3.27.7"
jspecify = "1.0.0"
junitJupiter = "6.0.2"
slf4j = "2.0.17"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-jupiter-bom = { module = "org.junit:junit-bom", version.ref = "junitJupiter" }
slf4j-bom = { module = "org.slf4j:slf4j-bom", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
